services:
  database:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_DATABASE: "emerchantPay"
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - 3306

