services:
#  web:
#    container_name: web
#    image: tomcat
#    volumes:
#      - //C\Users\Kiril\.m2\repository\com\example\demo1\0.0.1-SNAPSHOT\demo1-0.0.1-SNAPSHOT.jar
#    ports:
#      - '8082:8080'
#    environment:
#      MYSQL_DATABASE: "emerchantPay"
#      MYSQL_USER: root
#      MYSQL_ALLOW_EMPTY_PASSWORD: true
  database:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_DATABASE: "emerchantPay"
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - 3306

