services:
  database:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_DATABASE: "emerchantPay"
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306

